name: RevAI
description: An AI Code Reviewing Tool!
author: Sadra Yahyapour

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  name:
    required: false
    description: the person/thing you want to greet
    default: World

outputs:
  phrase:
    description: output variable
